CREATE TABLE TB_SHOHIN(
    SHOHIN_ID    CHAR(3)     NOT NULL,
    SHOHIN_NAME  VARCHAR(50) NOT NULL,
    TANKA        INTEGER default 0,
    CONSTRAINT pk_tb_shohin PRIMARY KEY(SHOHIN_ID)
);

CREATE TABLE T_KUYAKUSHO(
    ID        INTEGER     NOT NULL,
    KU        VARCHAR(20) NOT NULL,
    ZIP       VARCHAR(10) NOT NULL,
    ADDRESS   VARCHAR(50) NOT NULL,
    TEL       VARCHAR(20) NOT NULL,
    CONSTRAINT pk_t_kuyakusho PRIMARY KEY(ID)
);

CREATE TABLE USERINFO (
	USERID CHAR(20) CONSTRAINT PK_USERID PRIMARY KEY,
	PASSWORD VARCHAR(20) NOT NULL,
	GRANTID CHAR(2) NOT NULL,
	WORKPlACEID CHAR(2) NOT NULL,
	FAMILYNAME VARCHAR(20),
	FIRSTNAME VARCHAR(20)
);

commit;